apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
      - name: ping-pong-app
        image: heka27/ping-pong:0.2
        env:
          - name: PORT
            value: "3000"
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-pv
