apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/ingress.yaml
- todo-app/manifests/deployment.yaml
- todo-app/manifests/service.yaml
- todo-backend/manifests/cronjob.yaml
- todo-backend/manifests/deployment.yaml
- todo-backend/manifests/postgres-service.yaml
- todo-backend/manifests/service.yaml
- todo-backend/manifests/statefulset.yaml
- todo-backend/secret.yaml