apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: applications
  name: ping-pong-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
      - name: ping-pong-app
        image: heka27/ping-pong
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "3000"
