# Use Node.js-alpine as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the application files
COPY package.json index.js ./

# Run the application
CMD ["node", "index.js"]
