apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
data:
    POSTGRES_DB: ENC[AES256_GCM,data:LSwwNLat3bIMGA==,iv:HXs7Ry4L4YoRXxRZU1GRgdU+Oqi59Udo4hjlAN+5D+k=,tag:S4uzwWgfoOSr24f56jfc5A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:ICoVEtw=,iv:y6nYtfCazVBKcg74j9N1Kizfs3rtnNQWkx3/3MlB58U=,tag:UFZOLrkLu1S8mDLbECAahQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3nqUuime3l4=,iv:qUGApb4Brac6DhGzkH+ysnloDGSAtOyyInbMweY84uk=,tag:U9mkl4whtUwpNCrCjnP5Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a67qvr43g47zenpsy2usweayz756kuq76yfsmtjw4pl05dgl8e8qhfl6cr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNDNBUmpGcFF1TDVHT3Uv
            b0R4Vm9scXZNWG5hc3NqQTcvcnZOckdwdmo4CnRGcE9mV2hwc1F1dVNJRVNMcDlC
            M2tKNXhtemxkMFVISHhLN0k5RmNaVW8KLS0tIEwzaGY0V1RFTFQ0YTZ5Qy9zM0kx
            Y2lmTFc2VEo0ZVFhMXdPQXZ4TkIwelUKXQgecEoMjhWuDAXeaIZR3KZdlH3YgZxp
            l04Arl3blNe67tgOPDtGCup4zHQNP+t+UK0XZOIlEH7yujYvQVFwpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T13:04:03Z"
    mac: ENC[AES256_GCM,data:FJGjnE00Xh/sQZnytrJgSMZPsI0Oi9x0igJxsQS0M+HM+ns3Evth0zlX+oEDkq6VqY73slrBGN6DSA1JaaPfNwxLkNjMK/5xCIojera5CrlpZpcbYmwu05qoLMek0Uy2MLhFJvnMTPcdQpPM0+YfYWzIe8wiEBOtuB0L+ZFLt3U=,iv:dh7jMa9PAvgnRNprZy0u2q1PzR4uykBo1Thpd0XXwM4=,tag:yiGI2ajRBHras13aqDXncQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.4
