apiVersion: v1
kind: Service
metadata:
  namespace: applications
  name: ping-pong-svc
spec:
  type: LoadBalancer
  selector:
    app: ping-pong-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
