apiVersion: v1
kind: Service
metadata:
  namescape: applications
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output-app
  ports:
  - protocol: TCP
    port: 2345
    targetPort: 3000
