apiVersion: v1
kind: Service
metadata:
  namespace: applications
  name: postgres-svc
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
