apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: applications
  name: log-output-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
      - name: log-output-app
        image: heka27/log-output
        env:
        - name: PORT
          value: "3000"
        - name: PING_PONG_SERVICE_URL
          value: "http://ping-pong-svc:2345"
