apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec:
  type: ClusterIP
  selector:
    app: log-output-app
  ports:
  - protocol: TCP
    port: 2345        # Port exposed internally within the cluster
    targetPort: 3000  # Port the application is listening on
